### PR TITLE
Speeding up count_doubles()

### PR DESCRIPTION
**Pull request by purple-pixie**
Uses essentially the itertools 'pairwise' recipe to avoid duplicating the entire val list in memory.

### CODE REVIEW

**Comment by cuviper** [comment]
Can you show the new benchmark numbers?

I'd also suggest making this a new test variant to keep the old comparison around.

**Comment by rochacbruno** [comment]
I want to add an improved Python version, but `itertools.izip` is not available in Python 3 as the normal `zip` has been improved and took place of izip.

I implemented this:

```py
def count_doubles(val):
    total = 0
    for c1, c2 in zip(val, val[1:]):
        if c1 == c2:
            total += 1
    return total


def count_doubles_itertools(val):
    c1s, c2s = itertools.tee(val)
    next(c2s, None)
    total = 0
    for c1, c2 in zip(c1s, c2s):
        if c1 == c2:
            total += 1
    return total


double_re = re.compile(r'(?=(.)\1)')


def count_doubles_regex(val):
    return len(double_re.findall(val))
```

results:

```sh
--------------------------------------------------------------------------------- benchmark: 3 tests --------------------------------------------------------------------------------
Name (time in ms)         Min                Max               Mean            StdDev             Median               IQR            Outliers      OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_regex            24.7959 (1.0)      29.1496 (1.0)      25.4180 (1.0)      0.6717 (1.0)      25.3613 (1.0)      0.4590 (1.0)           1;1  39.3422 (1.0)          40           1
test_pure_python      48.9580 (1.97)     55.0126 (1.89)     49.9397 (1.96)     1.2816 (1.91)     49.6927 (1.96)     0.8554 (1.86)          1;1  20.0241 (0.51)         20           1
test_itertools        55.7509 (2.25)     60.5842 (2.08)     56.8567 (2.24)     1.2106 (1.80)     56.5401 (2.23)     1.1390 (2.48)          2;1  17.5881 (0.45)         17           1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

And your implementation is not better than pure_python.


Any other idea?

**Comment by cuviper** [comment]
Here's a python version similar to what I did in #3:

```python
def count_doubles_once(val):
    total = 0
    chars = iter(val)
    c1 = next(chars)
    for c2 in chars:
        if c1 == c2:
            total += 1
        c1 = c2
    return total
```

```
-------------------------------------------------------------------------------
Name (time in ms)             Min                Max               Mean        
-------------------------------------------------------------------------------
test_regex                14.2283 (1.0)      14.4368 (1.0)      14.2511 (1.0)  
test_pure_python_once     24.5366 (1.72)     25.1165 (1.74)     24.5808 (1.72) 
test_pure_python          32.7296 (2.30)     33.0272 (2.29)     32.7919 (2.30) 
-------------------------------------------------------------------------------
```

(I know "once" is not a great name -- feel free to take this and call it what you like...)

**Comment by purple-pixie** [comment]
I only have Python 2 on the machine I have to hand, so I imagine much of the speed up I experienced is from replacing the crappy old zip with izip, which was already done implicitly by Python 3. 

I cannot think why cloning the whole of val is faster than not doing that though, I'll have a further fiddle around and see what I can come up with.

**Comment by rochacbruno** [comment]
@cuviper I added your Python implementation https://github.com/rochacbruno/rust-python-example#new-results

**Pull request closed without merging**
